openapi: 3.1.0
info:
  title: Task Management API
  description: |
    REST API for managing user tasks with CRUD operations.
    All endpoints require JWT authentication via Bearer token.
    Tasks are scoped to the authenticated user (ownership enforced).
  version: 1.0.0
  contact:
    name: Spec-2 Task Management

servers:
  - url: /api
    description: API base path

security:
  - BearerAuth: []

paths:
  /{user_id}/tasks:
    get:
      summary: List all tasks
      description: Returns all tasks owned by the authenticated user
      operationId: listTasks
      tags:
        - Tasks
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskListResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'

    post:
      summary: Create a new task
      description: Creates a task owned by the authenticated user
      operationId: createTask
      tags:
        - Tasks
      parameters:
        - $ref: '#/components/parameters/UserId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'

  /{user_id}/tasks/{task_id}:
    get:
      summary: Get task details
      description: Returns a single task if owned by the authenticated user
      operationId: getTask
      tags:
        - Tasks
      parameters:
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/TaskId'
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      summary: Update a task
      description: Updates task title and/or description
      operationId: updateTask
      tags:
        - Tasks
      parameters:
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/TaskId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: Delete a task
      description: Permanently removes a task
      operationId: deleteTask
      tags:
        - Tasks
      parameters:
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/TaskId'
      responses:
        '204':
          description: Task deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /{user_id}/tasks/{task_id}/complete:
    patch:
      summary: Toggle task completion
      description: Toggles the is_complete status of a task
      operationId: toggleTaskComplete
      tags:
        - Tasks
      parameters:
        - $ref: '#/components/parameters/UserId'
        - $ref: '#/components/parameters/TaskId'
      responses:
        '200':
          description: Task completion toggled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token from Better Auth

  parameters:
    UserId:
      name: user_id
      in: path
      required: true
      description: User ID (must match authenticated user from JWT)
      schema:
        type: string

    TaskId:
      name: task_id
      in: path
      required: true
      description: Task ID
      schema:
        type: integer
        minimum: 1

  schemas:
    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
          description: Task title (required)
          example: "Buy groceries"
        description:
          type: string
          nullable: true
          description: Optional task description
          example: "Milk, eggs, bread"

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
          nullable: true
          description: New task title
          example: "Buy organic groceries"
        description:
          type: string
          nullable: true
          description: New task description
          example: "Organic milk, free-range eggs"

    TaskResponse:
      type: object
      required:
        - id
        - user_id
        - title
        - is_complete
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          description: Unique task identifier
          example: 1
        user_id:
          type: string
          description: Owner's user ID
          example: "user_abc123"
        title:
          type: string
          description: Task title
          example: "Buy groceries"
        description:
          type: string
          nullable: true
          description: Task description
          example: "Milk, eggs, bread"
        is_complete:
          type: boolean
          description: Completion status
          example: false
        created_at:
          type: string
          format: date-time
          description: Creation timestamp (UTC)
          example: "2026-01-17T10:30:00Z"
        updated_at:
          type: string
          format: date-time
          description: Last modification timestamp (UTC)
          example: "2026-01-17T10:30:00Z"

    TaskListResponse:
      type: object
      required:
        - tasks
        - count
      properties:
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/TaskResponse'
        count:
          type: integer
          description: Total number of tasks
          example: 3

    Error:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Human-readable error message
          example: "Task not found"

  responses:
    BadRequest:
      description: Invalid request payload
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: "Title is required"

    Unauthorized:
      description: Missing or invalid JWT token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: "Not authenticated"

    NotFound:
      description: Task not found or not owned by user
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: "Task not found"

tags:
  - name: Tasks
    description: Task CRUD operations with ownership enforcement
