openapi: 3.0.3
info:
  title: JWT Authentication API
  description: |
    Authentication endpoints for the Todo application.
    Implements JWT-based authentication per Constitution v1.0.0.
  version: 1.0.0
  contact:
    name: Todo App Team

servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.todoapp.com
    description: Production server

tags:
  - name: Authentication
    description: User signup, signin, and token operations

paths:
  /api/auth/signup:
    post:
      tags:
        - Authentication
      summary: Create new user account
      description: |
        Registers a new user with email and password.
        On success, automatically signs in the user and returns a JWT token.
        Returns generic error for duplicate emails (no enumeration).
      operationId: signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
            example:
              email: "user@example.com"
              password: "securepassword123"
      responses:
        '201':
          description: User created and signed in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Validation error (invalid email format or weak password)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '409':
          description: Registration failed (generic, no email enumeration)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Registration failed"

  /api/auth/signin:
    post:
      tags:
        - Authentication
      summary: Sign in existing user
      description: |
        Authenticates user with email and password.
        Returns JWT token on success.
        Returns generic error for invalid credentials (no enumeration).
      operationId: signin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInRequest'
            example:
              email: "user@example.com"
              password: "securepassword123"
      responses:
        '200':
          description: User signed in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Authentication failed (generic error)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Authentication failed"

  /api/auth/me:
    get:
      tags:
        - Authentication
      summary: Get current user
      description: |
        Returns the currently authenticated user.
        Requires valid JWT token in Authorization header.
      operationId: getCurrentUser
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Current user info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          description: Not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Could not validate credentials"

  /api/auth/verify:
    get:
      tags:
        - Authentication
      summary: Verify token validity
      description: |
        Verifies the JWT token is valid and not expired.
        Used by frontend to check session status.
      operationId: verifyToken
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Token is valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                    example: true
                  user_id:
                    type: integer
                    example: 1
        '401':
          description: Token is invalid or expired
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token from signin/signup response

  schemas:
    SignUpRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          maxLength: 255
          description: User's email address
          example: "user@example.com"
        password:
          type: string
          minLength: 8
          maxLength: 128
          description: User's password (min 8 characters)
          example: "securepassword123"

    SignInRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: User's email address
          example: "user@example.com"
        password:
          type: string
          description: User's password
          example: "securepassword123"

    UserResponse:
      type: object
      properties:
        id:
          type: integer
          description: Unique user identifier
          example: 1
        email:
          type: string
          format: email
          description: User's email address
          example: "user@example.com"
        created_at:
          type: string
          format: date-time
          description: Account creation timestamp
          example: "2026-01-11T12:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp
          example: "2026-01-11T12:00:00Z"

    AuthResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/UserResponse'
        token:
          type: string
          description: JWT access token
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

    Error:
      type: object
      properties:
        detail:
          type: string
          description: Error message
          example: "Authentication failed"

    ValidationError:
      type: object
      properties:
        detail:
          type: array
          items:
            type: object
            properties:
              loc:
                type: array
                items:
                  type: string
                description: Location of the error
              msg:
                type: string
                description: Error message
              type:
                type: string
                description: Error type
